import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from '../providers';
import Sidebar from '~/components/admin/Sidebar';
import Nav from '~/components/admin/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex min-h-screen">
            <Sidebar />
            <div className="flex-1">
              <Nav />
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
